-- 001_init.sql: Initial database schema and traceability spine.
--
-- Migration Policy: This is a forward-only script. Once applied to a live database, 
-- do not edit this file directly. All future schema changes must be handled via 
-- new sequentially numbered migrations (e.g., 002_add_new_table.sql).
--
-- Schema Naming Convention:
-- Table names have been standardized: 
-- obligations, controls, obligation_control_map, gaps, and remediations.
--
-- Structural Adjustments:
-- 1. Table Creation Order: `bank_entities` is created before `obligation_applicability` 
--    to resolve foreign key dependency issues and ensure the script compiles cleanly.
-- 2. Referential Integrity: `run_id` is implemented as a strict foreign key referencing 
--    the `runs(id)` table to maintain proper observability, rather than a standalone UUID.
--
-- Provenance & Audit Tracking:
-- Provenance columns are intentionally applied based on the specific tracking needs 
-- of each table, rather than a blanket application:
--   - `obligations` receives the full suite of provenance fields (including prompt versioning).
--   - `obligation_control_map` receives a slightly reduced subset.
--   - Downstream tables like `gaps` and `remediations` rely on limited tracking to 
--     balance auditability with system performance.

create extension if not exists "pgcrypto";  -- gen_random_uuid()

-- ============ Corpus ============
create table regulatory_documents (
  id uuid primary key default gen_random_uuid(),
  regulator text not null,                    -- BCBS | EU | PCI SSC | ...
  jurisdiction text not null,                  -- GLOBAL | EU | US | ...
  title text not null,
  doc_class text not null check (doc_class in
    ('regulation', 'guideline', 'standard', 'circular')),
  created_at timestamptz default now()
);

create table document_versions (
  id uuid primary key default gen_random_uuid(),
  document_id uuid not null references regulatory_documents(id),
  version_label text not null,                 -- 'v3.2.1' | '2024-consolidated'
  effective_date date,
  source_uri text,
  source_sha256 text not null,
  page_count int,
  ingest_run_id uuid,
  unique (document_id, version_label)
);

create table pages (
  id uuid primary key default gen_random_uuid(),
  document_version_id uuid not null references document_versions(id),
  page_no int not null,
  text_content text,
  -- reserved for the §6.3 D3 roadmap extension; unused/null in this F2/D2 submission:
  ocr_content text,
  extraction_method text not null default 'native',  -- native | ocr | vision | reconciled
  reconciliation_score numeric,
  unreadable boolean default false,
  image_uri text,
  unique (document_version_id, page_no)
);

create table clauses (
  id uuid primary key default gen_random_uuid(),
  document_version_id uuid not null references document_versions(id),
  clause_ref text not null,                    -- 'Art. 9(4)(a)' | '8.3.6'
  parent_clause_id uuid references clauses(id),
  text_content text not null,
  page_no int not null,
  bbox jsonb,
  char_span int4range,
  unique (document_version_id, clause_ref)
);

-- ============ Observability (moved up: obligations/mappings/assessments/gaps
-- all FK to runs(id) — the abridged §11 listing shows this section last, but
-- it has to exist before anything below can reference it) ============
create table runs (
  id uuid primary key default gen_random_uuid(),
  pipeline text not null,
  status text not null,
  started_at timestamptz default now(),
  finished_at timestamptz,
  total_cost_usd numeric default 0,
  config_snapshot jsonb
);

-- ============ Obligations ============
create table obligations (
  id uuid primary key default gen_random_uuid(),
  clause_id uuid not null references clauses(id),
  obligation_text text not null,
  verbatim_quote text not null,
  modality text not null check (modality in ('must', 'should', 'may', 'prohibited')),
  actor text,
  trigger_condition text,
  deadline_spec text,
  obligation_type text not null,
  -- provenance & verification (mandatory on every derived row, spec.md §11)
  confidence numeric not null,
  span_verified boolean not null default false,
  span_verify_method text,
  review_state text not null default 'proposed'
    check (review_state in ('proposed', 'accepted', 'rejected', 'needs_review')),
  created_by_agent text not null,
  model_id text not null,
  prompt_version text not null,
  run_id uuid not null references runs(id),
  scenario_id uuid,                            -- null = real spine; set = simulation (roadmap)
  -- source provenance (distinct from the execution-provenance columns above —
  -- see src/core/schemas.py's SourceProvenance docstring). Required keys
  -- enforced at the DB level too, not just by Pydantic.
  provenance jsonb not null
    check (provenance ? 'source_file' and provenance ? 'page_number' and provenance ? 'snippet_hash'),
  created_at timestamptz default now()
);
-- the invariant that carries the reliability claim (hard invariant #1):
alter table obligations add constraint accepted_requires_verified_span
  check (review_state <> 'accepted' or span_verified = true);

-- ============ Bank side (created before obligation_applicability, which
-- references bank_entities — see file-header note #1) ============
create table bank_entities (
  id uuid primary key default gen_random_uuid(),
  bank_id uuid not null,                       -- tenant/group-level id (spec.md §10.5) — not an FK, a partition key
  name text not null,
  jurisdiction text not null,
  licences text[] not null default '{}',
  product_lines text[] not null default '{}',
  parent_entity_id uuid references bank_entities(id)
);

create table obligation_applicability (
  id uuid primary key default gen_random_uuid(),
  obligation_id uuid not null references obligations(id),
  entity_id uuid not null references bank_entities(id),
  applies boolean not null,
  driver text not null,                        -- geography | licence | product | threshold
  rationale text not null,
  cited_profile_attribute text not null,       -- no unsupported applicability (spec.md §7.2.5)
  confidence numeric not null
);

create table controls (
  id uuid primary key default gen_random_uuid(),
  bank_id uuid not null,                       -- same tenant/group partition key as bank_entities.bank_id
  control_ref text not null,
  title text not null,
  design_description text,
  owner text,
  control_type text check (control_type in ('preventive', 'detective', 'corrective')),
  automation text check (automation in ('manual', 'semi', 'automated')),
  frequency text,
  source_policy_version_id uuid,               -- conceptually document_versions(id); spec.md §11 leaves it unconstrained
  source_page_no int,
  -- execution + source provenance, added for the invariant #4 resolution —
  -- spec.md §11 originally gave this table none at all (see schemas.py)
  confidence numeric not null,
  review_state text not null default 'proposed'
    check (review_state in ('proposed', 'accepted', 'rejected', 'needs_review')),
  created_by_agent text not null,
  model_id text not null,
  prompt_version text not null,
  run_id uuid not null references runs(id),
  scenario_id uuid,
  provenance jsonb not null
    check (provenance ? 'source_file' and provenance ? 'page_number' and provenance ? 'snippet_hash'),
  unique (bank_id, control_ref)
);

-- ============ Mapping, evidence, assessment ============
create table obligation_control_map (
  id uuid primary key default gen_random_uuid(),
  obligation_id uuid not null references obligations(id),
  control_id uuid not null references controls(id),
  coverage_level text not null check (coverage_level in ('full', 'partial', 'none')),
  rationale text not null,
  cited_control_span text,
  confidence numeric not null,
  review_state text not null default 'proposed'
    check (review_state in ('proposed', 'accepted', 'rejected', 'needs_review')),
  retrieval_rank int,
  rerank_score numeric,
  created_by_agent text not null,
  model_id text not null,
  prompt_version text not null,                -- added for the invariant #4 resolution (was missing)
  run_id uuid not null references runs(id),
  scenario_id uuid,
  provenance jsonb not null
    check (provenance ? 'source_file' and provenance ? 'page_number' and provenance ? 'snippet_hash'),
  unique (obligation_id, control_id, run_id)
);

create table evidence_artifacts (
  id uuid primary key default gen_random_uuid(),
  bank_id uuid not null,
  artifact_uri text not null,
  modality text not null,                      -- pdf|csv|xlsx|log active; png is roadmap (§6.3)
  period_start date,
  period_end date,
  extracted_facts jsonb,
  pii_flags jsonb
);

create table control_evidence_link (
  id uuid primary key default gen_random_uuid(),
  control_id uuid not null references controls(id),
  evidence_id uuid not null references evidence_artifacts(id),
  supports boolean not null,
  sufficiency text not null check (sufficiency in
    ('sufficient', 'partial', 'insufficient')),
  freshness_days int,
  rationale text not null,
  confidence numeric not null
);

create table control_assessments (
  id uuid primary key default gen_random_uuid(),
  control_id uuid not null references controls(id),
  design_effective boolean,
  operating_effective text check (operating_effective in ('true', 'false', 'unknown')),
  -- hard invariant #5: operating_effective may never be 'true' without a
  -- 'sufficient', in-window control_evidence_link row. That check requires a
  -- join across control_evidence_link, which a column-level CHECK constraint
  -- cannot express — spec.md §7.2.9 is explicit this is "enforced in code,
  -- not prompt," meaning application code (not yet built), not the DB either.
  basis text not null,
  exceptions jsonb,
  assessed_at timestamptz default now(),
  run_id uuid not null references runs(id),
  scenario_id uuid
);

-- ============ Gaps, remediation, monitoring ============
create table gaps (
  id uuid primary key default gen_random_uuid(),
  obligation_id uuid not null references obligations(id),
  entity_id uuid references bank_entities(id),
  gap_class text not null,
  narrative text not null,
  risk_factors jsonb not null,                 -- the 5 factors + rationales (config/risk.yaml)
  risk_score int not null,
  risk_band text not null,
  status text not null default 'open',
  review_state text not null default 'proposed'
    check (review_state in ('proposed', 'accepted', 'rejected', 'needs_review')),
  -- added for the invariant #4 resolution — spec.md §11 originally gave gaps
  -- no created_by_agent/model_id/confidence
  confidence numeric not null,
  created_by_agent text not null,
  model_id text not null,
  prompt_version text not null,
  run_id uuid not null references runs(id),
  scenario_id uuid,
  -- points at the triggering obligation's source — see schemas.py GapFinding
  -- docstring for why this is the least naturally well-defined of the 5
  provenance jsonb not null
    check (provenance ? 'source_file' and provenance ? 'page_number' and provenance ? 'snippet_hash')
);

create table remediations (
  id uuid primary key default gen_random_uuid(),
  gap_id uuid not null references gaps(id),
  action text not null,
  control_design_delta text,
  owner_role text,
  effort_estimate text,
  target_date date,
  test_plan text,
  status text not null default 'proposed',
  -- added for the invariant #4 resolution — spec.md §11 originally gave
  -- remediations no provenance/run_id at all
  confidence numeric not null,
  review_state text not null default 'proposed'
    check (review_state in ('proposed', 'accepted', 'rejected', 'needs_review')),
  created_by_agent text not null,
  model_id text not null,
  prompt_version text not null,
  run_id uuid not null references runs(id),
  scenario_id uuid,
  provenance jsonb not null
    check (provenance ? 'source_file' and provenance ? 'page_number' and provenance ? 'snippet_hash')
);

create table monitoring_items (
  id uuid primary key default gen_random_uuid(),
  obligation_id uuid references obligations(id),
  control_id uuid references controls(id),
  next_review_due date not null,
  trigger_conditions jsonb
);

-- ============ Change & cross-regulation (roadmap: §4 features 2/11/13/14 —
--              schema kept ready, no agent populates these this cycle) ============
create table clause_changes (
  id uuid primary key default gen_random_uuid(),
  from_version_id uuid not null references document_versions(id),
  to_version_id uuid not null references document_versions(id),
  old_clause_id uuid references clauses(id),
  new_clause_id uuid references clauses(id),
  change_type text not null check (change_type in
    ('added', 'removed', 'amended', 'renumbered', 'unchanged')),
  materiality text check (materiality in ('high', 'medium', 'low', 'editorial')),
  text_diff jsonb,
  rationale text
);

create table obligation_relations (
  id uuid primary key default gen_random_uuid(),
  obligation_a uuid not null references obligations(id),
  obligation_b uuid not null references obligations(id),
  relation_type text not null check (relation_type in
    ('overlaps', 'conflicts_with', 'supersedes', 'implements')),
  dimension text,                              -- retention|disclosure|timing|...
  rationale text not null,
  severity text,
  resolution_hint text,
  confidence numeric not null,
  check (obligation_a <> obligation_b)
);

-- ============ Observability & review (agent_steps/llm_calls/review_actions) ============
create table agent_steps (
  id bigserial primary key,
  run_id uuid not null references runs(id),
  node text not null,
  agent text not null,
  input_hash text,
  output_hash text,
  retry_count int default 0,
  verdict text,
  latency_ms int,
  error text,
  started_at timestamptz default now()
);

create table llm_calls (
  id bigserial primary key,
  run_id uuid not null references runs(id),
  step_id bigint references agent_steps(id),
  role text not null,                          -- EXTRACTOR|REASONER|JUDGE|SUMMARIZER
  model_id text not null,
  prompt_version text,
  prompt_tokens int,
  completion_tokens int,
  cost_usd numeric,
  latency_ms int,
  cache_hit boolean default false,
  -- added ahead of the Step-2 gateway build: spec.md §7.1.1 says every
  -- fallback invocation must be logged distinctly, not blended with primary
  -- calls. Not in spec.md §11's abridged listing; needed for what's being built.
  fallback_used boolean default false
);

create table review_actions (
  id bigserial primary key,
  entity_table text not null,                  -- polymorphic: not a real FK, can point at any table above
  entity_id uuid not null,
  reviewer text not null,
  action text not null,                        -- accept|reject|amend
  original_output jsonb,
  corrected_output jsonb,
  note text,
  created_at timestamptz default now()
);

-- ============ Indexes (B-tree on every foreign key) ============
create index idx_document_versions_document_id on document_versions(document_id);
create index idx_pages_document_version_id on pages(document_version_id);
create index idx_clauses_document_version_id on clauses(document_version_id);
create index idx_clauses_parent_clause_id on clauses(parent_clause_id);
create index idx_obligations_clause_id on obligations(clause_id);
create index idx_obligations_run_id on obligations(run_id);
create index idx_controls_run_id on controls(run_id);
create index idx_bank_entities_parent_entity_id on bank_entities(parent_entity_id);
create index idx_obligation_applicability_obligation_id on obligation_applicability(obligation_id);
create index idx_obligation_applicability_entity_id on obligation_applicability(entity_id);
create index idx_obligation_control_map_obligation_id on obligation_control_map(obligation_id);
create index idx_obligation_control_map_control_id on obligation_control_map(control_id);
create index idx_obligation_control_map_run_id on obligation_control_map(run_id);
create index idx_control_evidence_link_control_id on control_evidence_link(control_id);
create index idx_control_evidence_link_evidence_id on control_evidence_link(evidence_id);
create index idx_control_assessments_control_id on control_assessments(control_id);
create index idx_control_assessments_run_id on control_assessments(run_id);
create index idx_gaps_obligation_id on gaps(obligation_id);
create index idx_gaps_entity_id on gaps(entity_id);
create index idx_gaps_run_id on gaps(run_id);
create index idx_remediations_gap_id on remediations(gap_id);
create index idx_remediations_run_id on remediations(run_id);
create index idx_monitoring_items_obligation_id on monitoring_items(obligation_id);
create index idx_monitoring_items_control_id on monitoring_items(control_id);
create index idx_clause_changes_from_version_id on clause_changes(from_version_id);
create index idx_clause_changes_to_version_id on clause_changes(to_version_id);
create index idx_obligation_relations_obligation_a on obligation_relations(obligation_a);
create index idx_obligation_relations_obligation_b on obligation_relations(obligation_b);
create index idx_agent_steps_run_id on agent_steps(run_id);
create index idx_llm_calls_run_id on llm_calls(run_id);
create index idx_llm_calls_step_id on llm_calls(step_id);
create index idx_review_actions_entity on review_actions(entity_table, entity_id);
